apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podMetricsEndpoints:
    - port: "prometheus" # named port on which the Prometheus Webserver will be listening
      interval: 15s   # how often this endpoint should be scraped
  selector:
    matchLabels:    # set of labels to detect service objects by
      {{- toYaml .Values.labels | nindent 6 }}