apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: GitHubWebhooks
      rules:
        - alert: Non2XXStatusCode
          expr: gh_webhook_last_status_code_group{code_group!~"2xx|unused", status!="unused"} > 0
          {{- if .Values.alertLabels }}
          labels:
            {{- toYaml .Values.alertLabels | nindent 12 }}
          {{- end }}
          annotations:
            summary: |-
              '{{`Last seen status code for active/used webhook {{ $labels.webhook }} was non-2xx!`}}'
            description: |-
              {{`
              A non-2xx ({{ $labels.code_group }}) status code was returned for a webhook in repo <https://github.com/{{ $labels.repository }}/settings/hooks|{{ $labels.repository }}>
              Webhook: <https://github.com/{{ $labels.repository }}/settings/hooks/{{ $labels.webhook_id }}
              `}}

